// Backward-compatible re-export — all data now lives in data/ modules
export {
    LOCATIONS_CS, LOCATIONS_EN, LOCATIONS,
    HISTORY_SHORT_CS, HISTORY_SHORT_EN, HISTORY_SHORT,
    HISTORY_LONG_CS, HISTORY_LONG_EN, HISTORY_LONG,
    LIVE_FEED_MESSAGES,
    WHY_US_DATA_CS, WHY_US_DATA_EN, WHY_US_DATA,
    SERVICES_DATA_CS, SERVICES_DATA_EN, SERVICES_DATA,
    REVIEWS_DATA_CS, REVIEWS_DATA_EN, REVIEWS_DATA,
    PROTOCOL_DATA_CS, PROTOCOL_DATA_EN,
    EVENTS_DATA_CS, EVENTS_DATA_EN,
    DEFAULT_OWNER_PROFILE_CS, DEFAULT_OWNER_PROFILE_EN,
    SYSTEM_PROMPT
} from './data';
